---

# Manage Docker configuration

- name: 'Generate default file'
  become: True
  template:
    src: "{{ role_path }}/templates/default.j2"
    dest: "{{ docker_configuration_file_dest }}"
    mode: "{{ docker_configuration_file_mode }}"
    owner: "{{ docker_configuration_file_owner }}"
    group: "{{ docker_configuration_file_group }}"
  notify: 'restart docker'
