---

# RedHat family installation tasks

- name: 'INSTALL | YUM | Install dependencies'
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
  loop: "{{ docker_system_dependencies }}"


- name: 'INSTALL | YUM | Configure repository'
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgkey: "{{ item.gpgkey }}"
    gpgcheck: "{{ item.gpgcheck | default(True) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ docker_repositories }}"


- name: 'INSTALL | APT | Manage Docker packages'
  yum:
    name: "{{ item.name }}"
    version: "{{ item.version | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  notify: 'HANDLER | Restart docker'
  loop: "{{ docker_packages }}"
