---

# Defaults vars file for docker role

# Repositories and packages management
# -----------------------------------------------------------------------------

# Repositories
docker_repository_update_cache: True
docker_repository_cache_valid_time: 3600
docker_repository_keys_retries: 3
docker_repository_keys_delay: 10
docker_repositories: "{{ _docker_repositories }}"
docker_repositories_keys: "{{ _docker_repositories_keys }}"

# Packages
docker_packages: "{{ _docker_packages }}"
docker_system_dependencies: "{{ _docker_system_dependencies }}"

# Service settings
docker_service_name: 'docker'
docker_service_enabled: True
docker_service_state: 'started'

# Configuration
docker_paths:
  files:
    defaults:
      path: '/etc/default/docker'
    daemon_json:
      path: '/etc/docker/daemon.json'
    systemd_service:
      path: '/lib/systemd/system/docker.service'
  dirs:
    config:
      path: '/etc/docker'
    certs:
      path: '/etc/docker/certs.d'
    data:
      path: '/var/lib/docker'


# Docker registries certificates
# -----------------------------------------------------------------------------
docker_registries_certificates: []


# Docker daemon options
# -----------------------------------------------------------------------------
docker_daemon_options: "{{ _docker_daemon_options }}"
_docker_daemon_options:
  api-cors-header: ''
  bridge: ''
  bip: ''
  debug: False
  default-gateway: ''
  default-gateway-v6: ''
  cluster-store: ''
  cluster-advertise: ''
  cluster-store-opt: []
  dns: []
  dns-opt: []
  dns-search: []
  default-ulimit: []
  exec-opt: []
  exec-root: '/var/run/docker'
  fixed-cidr: ''
  fixed-cidr-v6: ''
  group: 'docker'
  data-root: '/var/lib/docker'
  hosts: []
  help: False
  icc: True
  insecure-registry: []
  ip: '0.0.0.0'
  ip-forward: True
  ip-masq: True
  iptables: True
  ipv6: False
  log-level: 'info'
  label: []
  log-driver: 'json-file'
  log-opt: []
  mtu: 0
  pidfile: '/var/run/docker.pid'
  registry-mirror: []
  selinux-enabled: False
  storage-driver: 'overlay2'
  storage-opt: []
  tls: False
  tlsverify: False
  userland-proxy: True
