---

dependency:
  name: 'galaxy'
driver:
  name: 'docker'
lint:
  name: 'yamllint'
platforms:
  - name: 'docker-docker-jessie'
    image: 'minimum2scp/systemd-jessie:latest'
    command: '/sbin/init'
    cap_add:
      - 'SYS_PTRACE'
    privileged: True
  - name: 'docker-docker-xenial'
    image: 'solita/ubuntu-systemd:16.04'
    command: '/sbin/init'
    cap_add:
      - 'SYS_PTRACE'
    privileged: True
provisioner:
  name: 'ansible'
  lint:
    name: 'ansible-lint'
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: '/usr/bin/env python2.7'
        docker_daemon_options:
          hosts:
            - 'tcp://127.0.0.1:8081'
            - 'unix:///var/run/docker.sock'
          tlscert: '/tmp/server.crt'
          tlskey: '/tmp/server.key'
    host_vars:
      docker-docker-jessie:
        docker_packages:
          - name: 'docker-ce=17.03*'
scenario:
  name: 'default'
verifier:
  name: 'testinfra'
  lint:
    name: 'flake8'
  options:
    sudo: True
